baseURL = "https://fengzdadi.github.io/"
languageCode = 'en-us'
title = "Fengze's Blog"
theme = "hugo-theme-stack"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
mainSections = ["post", "note", "essay","photo"]

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
post  = "/blog/:year/:slug/"
note  = "/notes/:year/:slug/"
essay = "/essay/:year/:slug/"
photos = "/photos/:year/:slug/"

[params.dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04"

[params.sidebar]
compact = false
emoji = "ğŸ¤”"
subtitle = "ä¸€ç”Ÿä¸€æ¬¡å°‘å¹´æ¸¸"
[params.sidebar.avatar]
enabled = true
src = "img/avatar.png"

[params.article]
headingAnchor = false
math = false
toc = true
readingTime = true
[params.article.license]
enabled = false
default = "CC BY-NC-SA 4.0"

[params.comments]
enabled = false
provider = "giscus"

[params.widgets]

[[params.widgets.homepage]]
type = "search"
params = {}

[[params.widgets.homepage]]
type = "categories"
params = { limit = 8 }

[[params.widgets.homepage]]
type = "tag-cloud"
params = { limit = 20 }

[[params.widgets.homepage]]
type = "archives"
params = { limit = 5 }

[[params.widgets.page]]
type = "toc"
params = {}

[[params.widgets.page]]
type = "tag-cloud"
params = { limit = 15 }

[[params.widgets.page]]
type = "archives"
params = { limit = 3 }

[params.opengraph]
[params.opengraph.twitter]
site = "fengzecai"
card = "summary_large_image"

[params.colorScheme]
default = "auto"
toggle = true

[params.footer]
since = 2025
customText = "Hello"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[menu.main.params]
icon = "home"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Fengzdadi"
weight = 1
[menu.social.params]
icon = "brand-github"

#[[menu.social]]
#identifier = "twitter"
#name = "X"
#url = "https://twitter.com/ä½ çš„è´¦å·"
#weight = 2
#[menu.social.params]
#icon = "brand-twitter"

[[menu.social]]
identifier = "email"
name = "Email"
url = "fengzcw@gmail.com"
weight = 8
[menu.social.params]
icon = "mail"


[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 2
[menu.main.params]
icon = "archives"

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 3
[menu.main.params]
icon = "search"

[[menu.main]]
identifier = "link"
name = "Link"
url = "/link/"
weight = 4
[menu.main.params]
icon = "link"

[[menu.main]]
identifier = "photos"
name = "Photos"
url = "/photos/"
weight = 5
[menu.main.params]
icon = "photo"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 6
[menu.main.params]
icon = "user"

# ä»£ç å—é«˜äº®
[markup]
[markup.highlight]
style = "rose-pine-dawn"  # è«å…°è¿ªé£æ ¼ä½é¥±å’Œä¸»é¢˜
noClasses = false

